# Generated by Django 4.2.3 on 2024-08-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='account_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
